server:
  port: ${PORT:10300}

spring:
  application:
    name: gateway-service
  profiles:
    active: ${CONFIG_PROFILE:development-local}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:10100}
  cloud:
    bus:
      enabled: true

    gateway:
      routes:
        - id: users-check
          uri: lb://users-service
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: users-create
          uri: lb://users-service
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: users-login
          uri: lb://users-service
          predicates:
            - Path=/users/security/login
            - Method=POST
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: users-get-edit-delete
          uri: lb://users-service
          predicates:
            - Path=/users/*
            - Method=GET,PUT,DELETE
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: products-check
          uri: lb://products-service
          predicates:
            - Path=/products/status/check
            - Method=GET
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}
        - id: products-categories-get
          uri: lb://products-service
          predicates:
            - Path=/categories, /categories/*, /products, /products/*
            - Method=GET
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: products-post-put
          uri: lb://products-service
          predicates:
            - Path=/categories, /categories/*, /products, /products/*
            - Method=POST,PUT,DELETE
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: comments-check
          uri: lb://comments-service
          predicates:
          - Path=/comments/status/check
          - Method=GET
          filters:
          - RewritePath=/comments/(?<segment>.*), /$\{segment}
        - id: comments-get-by-user
          uri: lb://comments-service
          predicates:
          - Path=/users/*/comments
          - Method=GET
          filters:
          - RewritePath=/users/(?<userId>.*)/comments, /users/$\{userId}/comments
        - id: comments-by-product
          uri: lb://comments-service
          predicates:
          - Path=/products/*/comments
          - Method=GET
          filters:
          - RewritePath=/products/(?<productId>.*)/comments, /products/$\{productId}/comments
        - id: comments-by-user-by-product
          uri: lb://comments-service
          predicates:
          - Path=/users/*/products/*/comments
          - Method=GET
          filters:
          - RewritePath=/users/(?<userId>.*)/products/(?<productId>.*)/comments, /users/$\{userId}/products/$\{productId}/comments
        - id: comments-post
          uri: lb://comments-service
          predicates:
          - Path=/comments
          - Method=POST
          filters:
            - RewritePath=/comments, /comments
        - id: comments-put-delete
          uri: lb://comments-service
          predicates:
            - Path=/comments/*
            - Method=PUT,DELETE
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test

security:
  origins:
    url: "*"
    max-age: 3600
    methods: GET, POST, PUT, DELETE, PATCH, OPTIONS, HEAD
    headers: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://guest:guest@localhost:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

# Must exposure only required uris
management:
  endpoints:
    web:
      exposure:
        include: "*"
