server:
  port: ${PORT:8012}

spring:
  application:
    name: gateway-service
  profiles:
    active: ${CONFIG_PROFILE:development-local}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8010}
  cloud:
    bus:
      enabled: true

    gateway:
      routes:
        - id: users-check
          uri: lb://users-service
          predicates:
            - Path=/users/status/check
            - Method=GET
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: users-create
          uri: lb://users-service
          predicates:
            - Path=/users
            - Method=POST
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: users-login
          uri: lb://users-service
          predicates:
            - Path=/users/security/login
            - Method=POST
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: users-edit-delete
          uri: lb://users-service
          predicates:
            - Path=/users/*
            - Method=GET,PUT,DELETE
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: products-check
          uri: lb://products-service
          predicates:
            - Path=/products/status/check
            - Method=GET
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}

  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test


eureka:
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8011/eureka

# Must exposure only required uris
management:
  endpoints:
    web:
      exposure:
        include: "*"
