server:
  port: ${PORT:10200}

spring:
  application:
    name: discovery-service
  profiles:
    active: ${CONFIG_PROFILE:development-local}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:10100}
  cloud:
    bus:
      enabled: true
  security:
    user:
      name: guest
      password: guest
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://guest:guest@localhost:10200/eureka
    registerWithEureka: false
    fetchRegistry: false
#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF

