server:
  port: ${PORT:10600}

spring:
  application:
    name: comments-service
  profiles:
    active: ${CONFIG_PROFILE:development-local}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:10100}
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
  datasource:
    url: jdbc:mysql://localhost:3306/users_products_comments?serverTimezone=UTC
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

logging:
  file:
    name: D:\\workspace\\project-users-products-comments-microservices-1\\logs\\${spring.application.name}.log

security:
  origins:
    url: "*"
    key: azerty123456
    max-age: 3600
    methods: GET, POST, PUT, DELETE
    headers: Origin, Content-Type, Accept, Authorization
  claims:
    header-authorities: Autorities
    separator: --
  token:
    key: 123
    type: Test
    header-name: token
    validity: 18000000

eureka:
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:10200/eureka

# Must exposure only required uris
management:
  endpoints:
    web:
      exposure:
        include: "*"
