eureka:
    client:
        serviceUrl:
            defaultZone: http://guest:guest@discovery:10200/eureka
            
spring:
    security:
        user:
            name: guest
            password: guest
    datasource:
        url: jdbc:mysql://database:3306/users_products_comments?serverTimezone=UTC
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest

security:
    origins:
        url: "*"
        key: azerty123456
        max-age: 3600
        methods: GET, POST, PUT, DELETE
        headers: Origin, Content-Type, Accept, Authorization
    claims:
        header-authorities: Autorities
        separator: --
    token:
        value: secret
        type: Bearer
        header-name: token
        validity: 18000000

    zipkin:
        base-url: http://zipkin:9411
        sender:
        type: web
    sleuth:
        sampler:
        probability: 1

    logging:
        file:
            name: /${spring.application.name}.log
        level:
            root: DEBUG        

feign:
    circuitbreaker:
        enabled: true
remote:
    services:
        comments: comments-service