eureka:
    client:
        serviceUrl:
            defaultZone: http://guest:guest@localhost:8011/eureka

spring:
    security:
        user:
            name: guest
            password: guest
    datasource:
        url: jdbc:mysql://localhost:3306/users_products_comments?serverTimezone=UTC
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

security:
    claims:
        header-authorities: Autorities
        separator: --
    token:
        value: secret
        type: Bearer
        header-name: token
        validity: 18000000

    zipkin:
        base-url: http://localhost:9411
        sender:
        type: web
    sleuth:
        sampler:
        probability: 1

    logging:
        file:
            name: D:\\workspace\\project-users-products-comments-microservices-1\\logs\\${spring.application.name}.log