eureka:
    client:
        serviceUrl:
            defaultZone: http://guest:guest@localhost:8011/eureka

spring:
    security:
        user:
            name: guest
            password: guest
    datasource:
        url: jdbc:mysql://localhost:3306/users_products_comments?serverTimezone=UTC
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

security:
  claims:
    header-autorities: Autorities
  token:
    value: secret
    type: Bearer
    header-name: token
    validity: 18000000