FROM openjdk:11
VOLUME /tmp
COPY target/configuration-server-0.0.1-SNAPSHOT.war configuration-server-0.0.1-SNAPSHOT.war
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","configuration-server-0.0.1-SNAPSHOT.war"]