version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    mem_limit: 700m
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices1
      
  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700m
    hostname: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices1

  database:
    image: mysql
    mem_limit: 700m
    hostname: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users_products_comments
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices1

networks:
  microservices1: